package meanreversion

import (
	"time"

	"github.com/dora-network/bond-trading-strategies/strategy/types"
	"github.com/govalues/decimal"
)

// Exit reason constants for ClosedTrade.
const (
	ExitReasonTakeProfit = "take_profit"
	ExitReasonStopLoss   = "stop_loss"
	ExitReasonForceClose = "force_close"
)

// TradeRecord captures a single simulated trade event (entry or exit)
// produced by the backtester.
type TradeRecord struct {
	Time         time.Time
	BondID       string
	Signal       types.Signal
	Spread       decimal.Decimal
	PositionSize decimal.Decimal
	ZScore       decimal.Decimal
	// Price is the bond price at which this trade was executed.
	Price decimal.Decimal
	// Quantity is the number of bonds traded (computed from the budget and
	// entry price).
	Quantity decimal.Decimal
	// EntryBalance is the remaining balance at the time the position was
	// opened, captured before any entry-side cash-flow adjustment.
	EntryBalance decimal.Decimal
}

// ClosedTrade records a completed round-trip trade and its PnL.
// PnL is expressed in spread-point terms: (EntrySpread − ExitSpread) for a BUY
// (we profited if the spread narrowed) or (ExitSpread − EntrySpread) for a SELL
// (we profited if the spread widened back).  Positive PnL = profit.
type ClosedTrade struct {
	BondID       string
	OpenTime     time.Time
	CloseTime    time.Time
	Signal       types.Signal // direction of the opening trade
	ExitSignal   types.Signal // signal generated by the strategy at exit time
	EntrySpread  decimal.Decimal
	ExitSpread   decimal.Decimal
	EntryZScore  decimal.Decimal
	ExitZScore   decimal.Decimal
	PositionSize decimal.Decimal
	PnL          decimal.Decimal
	ExitReason   string
	// EntryPrice is the bond price at which the position was opened.
	EntryPrice decimal.Decimal
	// ExitPrice is the bond price at which the position was closed.
	ExitPrice decimal.Decimal
	// Quantity is the number of bonds traded.
	Quantity decimal.Decimal
	// EntryBalance is the remaining balance at the time the position was
	// opened, before the trade budget was deducted. PnL is computed from
	// this value rather than from Quantity so that PositionSize only
	// controls position sizing and does not scale the PnL.
	EntryBalance decimal.Decimal
}

// BacktestResult summarises a full backtest run and implements the shared
// types.BacktestResult interface so the strategy server can read the result
// without depending on the mean-reversion package's concrete record shapes.
type BacktestResult struct {
	ClosedTrades []ClosedTrade
	TradeRecords []TradeRecord
	TotalPnL     decimal.Decimal
	WinCount     int
	LossCount    int
	MaxDrawdown  decimal.Decimal
	SharpeRatio  decimal.Decimal // annualised, assumes daily observations
}

func (r BacktestResult) GetTotalPnL() decimal.Decimal    { return r.TotalPnL }
func (r BacktestResult) GetWinCount() int                { return r.WinCount }
func (r BacktestResult) GetLossCount() int               { return r.LossCount }
func (r BacktestResult) GetMaxDrawdown() decimal.Decimal { return r.MaxDrawdown }
func (r BacktestResult) GetSharpeRatio() decimal.Decimal { return r.SharpeRatio }
func (r BacktestResult) GetTradeRecords() any            { return r.TradeRecords }
func (r BacktestResult) GetClosedTrades() any            { return r.ClosedTrades }

var _ types.BacktestResult = BacktestResult{}
