// Code generated by counterfeiter. DO NOT EDIT.
package breakoutfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/strategy/types"
)

type FakeHistoricalPriceStore struct {
	ObservationsStub        func(context.Context, string, time.Time, time.Time) ([]types.YieldObservation, error)
	observationsMutex       sync.RWMutex
	observationsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}
	observationsReturns struct {
		result1 []types.YieldObservation
		result2 error
	}
	observationsReturnsOnCall map[int]struct {
		result1 []types.YieldObservation
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHistoricalPriceStore) Observations(arg1 context.Context, arg2 string, arg3 time.Time, arg4 time.Time) ([]types.YieldObservation, error) {
	fake.observationsMutex.Lock()
	ret, specificReturn := fake.observationsReturnsOnCall[len(fake.observationsArgsForCall)]
	fake.observationsArgsForCall = append(fake.observationsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.ObservationsStub
	fakeReturns := fake.observationsReturns
	fake.recordInvocation("Observations", []interface{}{arg1, arg2, arg3, arg4})
	fake.observationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHistoricalPriceStore) ObservationsCallCount() int {
	fake.observationsMutex.RLock()
	defer fake.observationsMutex.RUnlock()
	return len(fake.observationsArgsForCall)
}

func (fake *FakeHistoricalPriceStore) ObservationsCalls(stub func(context.Context, string, time.Time, time.Time) ([]types.YieldObservation, error)) {
	fake.observationsMutex.Lock()
	defer fake.observationsMutex.Unlock()
	fake.ObservationsStub = stub
}

func (fake *FakeHistoricalPriceStore) ObservationsArgsForCall(i int) (context.Context, string, time.Time, time.Time) {
	fake.observationsMutex.RLock()
	defer fake.observationsMutex.RUnlock()
	argsForCall := fake.observationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeHistoricalPriceStore) ObservationsReturns(result1 []types.YieldObservation, result2 error) {
	fake.observationsMutex.Lock()
	defer fake.observationsMutex.Unlock()
	fake.ObservationsStub = nil
	fake.observationsReturns = struct {
		result1 []types.YieldObservation
		result2 error
	}{result1, result2}
}

func (fake *FakeHistoricalPriceStore) ObservationsReturnsOnCall(i int, result1 []types.YieldObservation, result2 error) {
	fake.observationsMutex.Lock()
	defer fake.observationsMutex.Unlock()
	fake.ObservationsStub = nil
	if fake.observationsReturnsOnCall == nil {
		fake.observationsReturnsOnCall = make(map[int]struct {
			result1 []types.YieldObservation
			result2 error
		})
	}
	fake.observationsReturnsOnCall[i] = struct {
		result1 []types.YieldObservation
		result2 error
	}{result1, result2}
}

func (fake *FakeHistoricalPriceStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHistoricalPriceStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
