// Package orderbroker submits orders to Dora under the user's
// stored API key. The broker is a thin wrapper around the
// doraclient.APIClient from github.com/dora-network/dora-client-go; one client
// per agent process, per-request auth via context value.
//
// The Intent type matches dora-strategy-wasm's
// dorastrategy.OrderIntent (and therefore Dora's
// CreateOrderRequest): decimal strings for quantities, prices,
// and leverage, with FromGlobalPosition defaulting to false
// (isolated margin account) and InverseLeverage defaulting to
// "1" (no leverage) when the strategy leaves the field empty.
package orderbroker

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/google/uuid"

	"github.com/dora-network/dora-client-go/doraclient"
)

// Intent is the host-side mirror of dora-strategy-wasm's
// dorastrategy.OrderIntent. It is constructed by the WASM
// host-call implementation when a plugin's host_submit_order
// fires.
type Intent struct {
	OrderBookID        string
	Side               string // "buy" | "sell" (mapped to "BUY" | "SELL")
	Quantity           string // decimal string
	Type               string // "market" | "limit" (mapped to "MARKET" | "LIMIT")
	Price              string // required for limit; ignored (never sent) for market
	InverseLeverage    string // empty => host default "1" (no leverage)
	FromGlobalPosition bool   // false (default) => isolated margin; true => global cash
}

// Result is the broker's response. The order ID is taken from
// the CreateOrderResponseEnvelope.Data.OrderId. The ClientOrderID
// is the broker-generated id stamped onto the request and echoed
// back so the caller can correlate broker-side state with the
// outbound REST call.
type Result struct {
	OrderID       string
	ClientOrderID string
}

// Errors
var (
	ErrEmptyAPIKey  = errors.New("orderbroker: empty API key")
	ErrEmptyOrderID = errors.New("orderbroker: empty order ID")
)

// Broker wraps a single doraclient.APIClient and submits orders
// under per-request user API keys. The client is shared with
// the rest of the agent (e.g. auth.NewSDKDoraClient); the broker
// builds per-request auth contexts on every call.
type Broker struct {
	api *doraclient.APIClient
}

// New constructs a Broker around the given SDK client.
func New(api *doraclient.APIClient) *Broker {
	return &Broker{api: api}
}

// SubmitOrder sends an order intent to Dora under the user's key.
// The call is synchronous: the plugin blocks until the order is
// acked (orderID returned) or denied (typed error returned).
//
// ClientOrderID is generated by the broker on every call so the
// outbound REST request is idempotent and the resulting order can
// be traced back to a specific (user, strategy) invocation. The
// format is `dora-agent_{user_id}_{strategy_id}_{uuid_v7}` —
// `dora-agent` identifies the source service, the underscored
// fields split cleanly into the four parts since UUIDv7 contains
// hyphens, and the UUIDv7 suffix gives chronological ordering
// within a (user, strategy) pair.
//
// Mapping from intent to CreateOrderRequest:
//
//	Side               "buy"/"sell"     -> "BUY"/"SELL"
//	Type               "market"/"limit" -> "MARKET"/"LIMIT"
//	Quantity, Price,
//	  InverseLeverage  string           -> string (decimal)
//	FromGlobalPosition bool             -> bool
//
// InverseLeverage defaults to "1" (no leverage) when the strategy
// leaves it empty; the SDK requires a non-empty string.
// FromGlobalPosition defaults to false (isolated margin) per the
// product decision: orders are always submitted from the user's
// isolated margin account unless the strategy explicitly opts
// into the global cash account.
func (b *Broker) SubmitOrder(ctx context.Context, userID, strategyID, apiKey string, intent Intent) (Result, error) {
	if apiKey == "" {
		return Result{}, ErrEmptyAPIKey
	}
	if intent.OrderBookID == "" || intent.Quantity == "" || intent.Side == "" || intent.Type == "" {
		return Result{}, fmt.Errorf("orderbroker: missing required intent field: %+v", intent)
	}

	leverage := intent.InverseLeverage
	if leverage == "" {
		leverage = "1"
	}

	id, err := uuid.NewV7()
	if err != nil {
		return Result{}, fmt.Errorf("orderbroker: client order id: %w", err)
	}
	clientOrderID := fmt.Sprintf("dora-agent_%s_%s_%s", userID, strategyID, id)

	req := doraclient.NewCreateOrderRequest(
		intent.Quantity,
		leverage,
		doraclient.OrderKind(strings.ToUpper(intent.Type)),
		doraclient.Side(strings.ToUpper(intent.Side)),
		intent.FromGlobalPosition,
		intent.OrderBookID,
	)
	req.SetClientOrderId(clientOrderID)
	// Price is only meaningful for LIMIT orders. Per the dora-api
	// ValidateSubmitOrderRequest contract: if kind is LIMIT, price
	// must be > 0; if MARKET it must be 0 or omitted. The SDK
	// accepts a *string pointer; we leave it nil for market orders
	// regardless of what the strategy provided. The Price field on
	// a market-order intent is silently ignored; a future tightening
	// of the server-side validation will not trip on it.
	if strings.EqualFold(intent.Type, "limit") && intent.Price != "" {
		req.SetPrice(intent.Price)
	}

	authCtx := withAPIKey(ctx, apiKey)
	env, httpResp, err := b.api.DefaultAPI.CreateOrder(authCtx).CreateOrderRequest(*req).Execute()
	if err != nil {
		_ = httpResp.Body.Close()
		return Result{}, fmt.Errorf("orderbroker: create order: %w (status=%d)", err, statusCode(httpResp))
	}
	if env == nil || env.Data == nil || env.Data.OrderId == nil {
		return Result{}, errors.New("orderbroker: empty order id in response")
	}
	return Result{OrderID: *env.Data.OrderId, ClientOrderID: clientOrderID}, nil
}

// CancelOrder cancels a previously submitted order by ID.
// Returns nil on success, an error on REST failure or denial.
func (b *Broker) CancelOrder(ctx context.Context, userID, apiKey, orderID string) error {
	if apiKey == "" {
		return ErrEmptyAPIKey
	}
	if orderID == "" {
		return ErrEmptyOrderID
	}
	authCtx := withAPIKey(ctx, apiKey)
	_, httpResp, err := b.api.DefaultAPI.CancelOrderById(authCtx, orderID).Execute()
	if err != nil {
		_ = httpResp.Body.Close()
		return fmt.Errorf("orderbroker: cancel order: %w (status=%d)", err, statusCode(httpResp))
	}
	return nil
}

// withAPIKey attaches the user's API key to the request context
// in the form the doraclient SDK expects. The SDK reads
// doraclient.ContextAPIKeys out of the context and emits
// "Authorization: <Prefix> <Key>" — Prefix "ApiKey" is what Dora
// requires.
func withAPIKey(ctx context.Context, key string) context.Context {
	return context.WithValue(ctx, doraclient.ContextAPIKeys, map[string]doraclient.APIKey{
		"apiKeyAuthHeader": {Key: key, Prefix: "ApiKey"},
	})
}

// statusCode returns the HTTP status code from a response, or 0
// if the response is nil. Used for richer error messages.
func statusCode(resp *http.Response) int {
	if resp == nil {
		return 0
	}
	return resp.StatusCode
}
