// Code generated by counterfeiter. DO NOT EDIT.
package strategyfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/candles"
	"github.com/dora-network/bond-trading-strategies/strategy"
	"github.com/dora-network/bond-trading-strategies/strategy/types"
	"github.com/google/uuid"
)

type FakeCandleFeed struct {
	SubscribeBarsStub        func(context.Context, uuid.UUID, candles.Resolution, time.Time) (<-chan types.Bar, func(), error)
	subscribeBarsMutex       sync.RWMutex
	subscribeBarsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 candles.Resolution
		arg4 time.Time
	}
	subscribeBarsReturns struct {
		result1 <-chan types.Bar
		result2 func()
		result3 error
	}
	subscribeBarsReturnsOnCall map[int]struct {
		result1 <-chan types.Bar
		result2 func()
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCandleFeed) SubscribeBars(arg1 context.Context, arg2 uuid.UUID, arg3 candles.Resolution, arg4 time.Time) (<-chan types.Bar, func(), error) {
	fake.subscribeBarsMutex.Lock()
	ret, specificReturn := fake.subscribeBarsReturnsOnCall[len(fake.subscribeBarsArgsForCall)]
	fake.subscribeBarsArgsForCall = append(fake.subscribeBarsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 candles.Resolution
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.SubscribeBarsStub
	fakeReturns := fake.subscribeBarsReturns
	fake.recordInvocation("SubscribeBars", []interface{}{arg1, arg2, arg3, arg4})
	fake.subscribeBarsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCandleFeed) SubscribeBarsCallCount() int {
	fake.subscribeBarsMutex.RLock()
	defer fake.subscribeBarsMutex.RUnlock()
	return len(fake.subscribeBarsArgsForCall)
}

func (fake *FakeCandleFeed) SubscribeBarsCalls(stub func(context.Context, uuid.UUID, candles.Resolution, time.Time) (<-chan types.Bar, func(), error)) {
	fake.subscribeBarsMutex.Lock()
	defer fake.subscribeBarsMutex.Unlock()
	fake.SubscribeBarsStub = stub
}

func (fake *FakeCandleFeed) SubscribeBarsArgsForCall(i int) (context.Context, uuid.UUID, candles.Resolution, time.Time) {
	fake.subscribeBarsMutex.RLock()
	defer fake.subscribeBarsMutex.RUnlock()
	argsForCall := fake.subscribeBarsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeCandleFeed) SubscribeBarsReturns(result1 <-chan types.Bar, result2 func(), result3 error) {
	fake.subscribeBarsMutex.Lock()
	defer fake.subscribeBarsMutex.Unlock()
	fake.SubscribeBarsStub = nil
	fake.subscribeBarsReturns = struct {
		result1 <-chan types.Bar
		result2 func()
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCandleFeed) SubscribeBarsReturnsOnCall(i int, result1 <-chan types.Bar, result2 func(), result3 error) {
	fake.subscribeBarsMutex.Lock()
	defer fake.subscribeBarsMutex.Unlock()
	fake.SubscribeBarsStub = nil
	if fake.subscribeBarsReturnsOnCall == nil {
		fake.subscribeBarsReturnsOnCall = make(map[int]struct {
			result1 <-chan types.Bar
			result2 func()
			result3 error
		})
	}
	fake.subscribeBarsReturnsOnCall[i] = struct {
		result1 <-chan types.Bar
		result2 func()
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCandleFeed) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCandleFeed) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ strategy.CandleFeed = new(FakeCandleFeed)
