// Code generated by counterfeiter. DO NOT EDIT.
package strategyfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/strategy"
	"github.com/dora-network/bond-trading-strategies/strategy/types"
	"github.com/google/uuid"
)

type FakeStrategy struct {
	BacktestStub        func(context.Context, time.Time, time.Time) (types.BacktestResult, error)
	backtestMutex       sync.RWMutex
	backtestArgsForCall []struct {
		arg1 context.Context
		arg2 time.Time
		arg3 time.Time
	}
	backtestReturns struct {
		result1 types.BacktestResult
		result2 error
	}
	backtestReturnsOnCall map[int]struct {
		result1 types.BacktestResult
		result2 error
	}
	RunStub        func(context.Context, <-chan strategy.Message, uuid.UUID) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
		arg2 <-chan strategy.Message
		arg3 uuid.UUID
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStrategy) Backtest(arg1 context.Context, arg2 time.Time, arg3 time.Time) (types.BacktestResult, error) {
	fake.backtestMutex.Lock()
	ret, specificReturn := fake.backtestReturnsOnCall[len(fake.backtestArgsForCall)]
	fake.backtestArgsForCall = append(fake.backtestArgsForCall, struct {
		arg1 context.Context
		arg2 time.Time
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.BacktestStub
	fakeReturns := fake.backtestReturns
	fake.recordInvocation("Backtest", []interface{}{arg1, arg2, arg3})
	fake.backtestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStrategy) BacktestCallCount() int {
	fake.backtestMutex.RLock()
	defer fake.backtestMutex.RUnlock()
	return len(fake.backtestArgsForCall)
}

func (fake *FakeStrategy) BacktestCalls(stub func(context.Context, time.Time, time.Time) (types.BacktestResult, error)) {
	fake.backtestMutex.Lock()
	defer fake.backtestMutex.Unlock()
	fake.BacktestStub = stub
}

func (fake *FakeStrategy) BacktestArgsForCall(i int) (context.Context, time.Time, time.Time) {
	fake.backtestMutex.RLock()
	defer fake.backtestMutex.RUnlock()
	argsForCall := fake.backtestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStrategy) BacktestReturns(result1 types.BacktestResult, result2 error) {
	fake.backtestMutex.Lock()
	defer fake.backtestMutex.Unlock()
	fake.BacktestStub = nil
	fake.backtestReturns = struct {
		result1 types.BacktestResult
		result2 error
	}{result1, result2}
}

func (fake *FakeStrategy) BacktestReturnsOnCall(i int, result1 types.BacktestResult, result2 error) {
	fake.backtestMutex.Lock()
	defer fake.backtestMutex.Unlock()
	fake.BacktestStub = nil
	if fake.backtestReturnsOnCall == nil {
		fake.backtestReturnsOnCall = make(map[int]struct {
			result1 types.BacktestResult
			result2 error
		})
	}
	fake.backtestReturnsOnCall[i] = struct {
		result1 types.BacktestResult
		result2 error
	}{result1, result2}
}

func (fake *FakeStrategy) Run(arg1 context.Context, arg2 <-chan strategy.Message, arg3 uuid.UUID) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
		arg2 <-chan strategy.Message
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2, arg3})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStrategy) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeStrategy) RunCalls(stub func(context.Context, <-chan strategy.Message, uuid.UUID) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeStrategy) RunArgsForCall(i int) (context.Context, <-chan strategy.Message, uuid.UUID) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStrategy) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStrategy) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStrategy) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStrategy) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ strategy.Strategy = new(FakeStrategy)
