// Code generated by counterfeiter. DO NOT EDIT.
package strategyfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/strategy"
	"github.com/dora-network/bond-trading-strategies/strategy/types"
	"github.com/google/uuid"
)

type FakeService struct {
	BaseContextStub        func() context.Context
	baseContextMutex       sync.RWMutex
	baseContextArgsForCall []struct {
	}
	baseContextReturns struct {
		result1 context.Context
	}
	baseContextReturnsOnCall map[int]struct {
		result1 context.Context
	}
	PauseStrategyStub        func(context.Context, uuid.UUID) error
	pauseStrategyMutex       sync.RWMutex
	pauseStrategyArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	pauseStrategyReturns struct {
		result1 error
	}
	pauseStrategyReturnsOnCall map[int]struct {
		result1 error
	}
	ResumeStrategyStub        func(context.Context, uuid.UUID) error
	resumeStrategyMutex       sync.RWMutex
	resumeStrategyArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	resumeStrategyReturns struct {
		result1 error
	}
	resumeStrategyReturnsOnCall map[int]struct {
		result1 error
	}
	RunBacktestStub        func(context.Context, uuid.UUID, strategy.Strategy, time.Time, time.Time) (<-chan types.BacktestResult, error)
	runBacktestMutex       sync.RWMutex
	runBacktestArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 strategy.Strategy
		arg4 time.Time
		arg5 time.Time
	}
	runBacktestReturns struct {
		result1 <-chan types.BacktestResult
		result2 error
	}
	runBacktestReturnsOnCall map[int]struct {
		result1 <-chan types.BacktestResult
		result2 error
	}
	RunStrategyStub        func(context.Context, strategy.Strategy) (uuid.UUID, error)
	runStrategyMutex       sync.RWMutex
	runStrategyArgsForCall []struct {
		arg1 context.Context
		arg2 strategy.Strategy
	}
	runStrategyReturns struct {
		result1 uuid.UUID
		result2 error
	}
	runStrategyReturnsOnCall map[int]struct {
		result1 uuid.UUID
		result2 error
	}
	StopBacktestStub        func(uuid.UUID) error
	stopBacktestMutex       sync.RWMutex
	stopBacktestArgsForCall []struct {
		arg1 uuid.UUID
	}
	stopBacktestReturns struct {
		result1 error
	}
	stopBacktestReturnsOnCall map[int]struct {
		result1 error
	}
	StopStrategyStub        func(context.Context, uuid.UUID) error
	stopStrategyMutex       sync.RWMutex
	stopStrategyArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	stopStrategyReturns struct {
		result1 error
	}
	stopStrategyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) BaseContext() context.Context {
	fake.baseContextMutex.Lock()
	ret, specificReturn := fake.baseContextReturnsOnCall[len(fake.baseContextArgsForCall)]
	fake.baseContextArgsForCall = append(fake.baseContextArgsForCall, struct {
	}{})
	stub := fake.BaseContextStub
	fakeReturns := fake.baseContextReturns
	fake.recordInvocation("BaseContext", []interface{}{})
	fake.baseContextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) BaseContextCallCount() int {
	fake.baseContextMutex.RLock()
	defer fake.baseContextMutex.RUnlock()
	return len(fake.baseContextArgsForCall)
}

func (fake *FakeService) BaseContextCalls(stub func() context.Context) {
	fake.baseContextMutex.Lock()
	defer fake.baseContextMutex.Unlock()
	fake.BaseContextStub = stub
}

func (fake *FakeService) BaseContextReturns(result1 context.Context) {
	fake.baseContextMutex.Lock()
	defer fake.baseContextMutex.Unlock()
	fake.BaseContextStub = nil
	fake.baseContextReturns = struct {
		result1 context.Context
	}{result1}
}

func (fake *FakeService) BaseContextReturnsOnCall(i int, result1 context.Context) {
	fake.baseContextMutex.Lock()
	defer fake.baseContextMutex.Unlock()
	fake.BaseContextStub = nil
	if fake.baseContextReturnsOnCall == nil {
		fake.baseContextReturnsOnCall = make(map[int]struct {
			result1 context.Context
		})
	}
	fake.baseContextReturnsOnCall[i] = struct {
		result1 context.Context
	}{result1}
}

func (fake *FakeService) PauseStrategy(arg1 context.Context, arg2 uuid.UUID) error {
	fake.pauseStrategyMutex.Lock()
	ret, specificReturn := fake.pauseStrategyReturnsOnCall[len(fake.pauseStrategyArgsForCall)]
	fake.pauseStrategyArgsForCall = append(fake.pauseStrategyArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.PauseStrategyStub
	fakeReturns := fake.pauseStrategyReturns
	fake.recordInvocation("PauseStrategy", []interface{}{arg1, arg2})
	fake.pauseStrategyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) PauseStrategyCallCount() int {
	fake.pauseStrategyMutex.RLock()
	defer fake.pauseStrategyMutex.RUnlock()
	return len(fake.pauseStrategyArgsForCall)
}

func (fake *FakeService) PauseStrategyCalls(stub func(context.Context, uuid.UUID) error) {
	fake.pauseStrategyMutex.Lock()
	defer fake.pauseStrategyMutex.Unlock()
	fake.PauseStrategyStub = stub
}

func (fake *FakeService) PauseStrategyArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.pauseStrategyMutex.RLock()
	defer fake.pauseStrategyMutex.RUnlock()
	argsForCall := fake.pauseStrategyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) PauseStrategyReturns(result1 error) {
	fake.pauseStrategyMutex.Lock()
	defer fake.pauseStrategyMutex.Unlock()
	fake.PauseStrategyStub = nil
	fake.pauseStrategyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) PauseStrategyReturnsOnCall(i int, result1 error) {
	fake.pauseStrategyMutex.Lock()
	defer fake.pauseStrategyMutex.Unlock()
	fake.PauseStrategyStub = nil
	if fake.pauseStrategyReturnsOnCall == nil {
		fake.pauseStrategyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pauseStrategyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ResumeStrategy(arg1 context.Context, arg2 uuid.UUID) error {
	fake.resumeStrategyMutex.Lock()
	ret, specificReturn := fake.resumeStrategyReturnsOnCall[len(fake.resumeStrategyArgsForCall)]
	fake.resumeStrategyArgsForCall = append(fake.resumeStrategyArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ResumeStrategyStub
	fakeReturns := fake.resumeStrategyReturns
	fake.recordInvocation("ResumeStrategy", []interface{}{arg1, arg2})
	fake.resumeStrategyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ResumeStrategyCallCount() int {
	fake.resumeStrategyMutex.RLock()
	defer fake.resumeStrategyMutex.RUnlock()
	return len(fake.resumeStrategyArgsForCall)
}

func (fake *FakeService) ResumeStrategyCalls(stub func(context.Context, uuid.UUID) error) {
	fake.resumeStrategyMutex.Lock()
	defer fake.resumeStrategyMutex.Unlock()
	fake.ResumeStrategyStub = stub
}

func (fake *FakeService) ResumeStrategyArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.resumeStrategyMutex.RLock()
	defer fake.resumeStrategyMutex.RUnlock()
	argsForCall := fake.resumeStrategyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ResumeStrategyReturns(result1 error) {
	fake.resumeStrategyMutex.Lock()
	defer fake.resumeStrategyMutex.Unlock()
	fake.ResumeStrategyStub = nil
	fake.resumeStrategyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ResumeStrategyReturnsOnCall(i int, result1 error) {
	fake.resumeStrategyMutex.Lock()
	defer fake.resumeStrategyMutex.Unlock()
	fake.ResumeStrategyStub = nil
	if fake.resumeStrategyReturnsOnCall == nil {
		fake.resumeStrategyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resumeStrategyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) RunBacktest(arg1 context.Context, arg2 uuid.UUID, arg3 strategy.Strategy, arg4 time.Time, arg5 time.Time) (<-chan types.BacktestResult, error) {
	fake.runBacktestMutex.Lock()
	ret, specificReturn := fake.runBacktestReturnsOnCall[len(fake.runBacktestArgsForCall)]
	fake.runBacktestArgsForCall = append(fake.runBacktestArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 strategy.Strategy
		arg4 time.Time
		arg5 time.Time
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RunBacktestStub
	fakeReturns := fake.runBacktestReturns
	fake.recordInvocation("RunBacktest", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.runBacktestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) RunBacktestCallCount() int {
	fake.runBacktestMutex.RLock()
	defer fake.runBacktestMutex.RUnlock()
	return len(fake.runBacktestArgsForCall)
}

func (fake *FakeService) RunBacktestCalls(stub func(context.Context, uuid.UUID, strategy.Strategy, time.Time, time.Time) (<-chan types.BacktestResult, error)) {
	fake.runBacktestMutex.Lock()
	defer fake.runBacktestMutex.Unlock()
	fake.RunBacktestStub = stub
}

func (fake *FakeService) RunBacktestArgsForCall(i int) (context.Context, uuid.UUID, strategy.Strategy, time.Time, time.Time) {
	fake.runBacktestMutex.RLock()
	defer fake.runBacktestMutex.RUnlock()
	argsForCall := fake.runBacktestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeService) RunBacktestReturns(result1 <-chan types.BacktestResult, result2 error) {
	fake.runBacktestMutex.Lock()
	defer fake.runBacktestMutex.Unlock()
	fake.RunBacktestStub = nil
	fake.runBacktestReturns = struct {
		result1 <-chan types.BacktestResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) RunBacktestReturnsOnCall(i int, result1 <-chan types.BacktestResult, result2 error) {
	fake.runBacktestMutex.Lock()
	defer fake.runBacktestMutex.Unlock()
	fake.RunBacktestStub = nil
	if fake.runBacktestReturnsOnCall == nil {
		fake.runBacktestReturnsOnCall = make(map[int]struct {
			result1 <-chan types.BacktestResult
			result2 error
		})
	}
	fake.runBacktestReturnsOnCall[i] = struct {
		result1 <-chan types.BacktestResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) RunStrategy(arg1 context.Context, arg2 strategy.Strategy) (uuid.UUID, error) {
	fake.runStrategyMutex.Lock()
	ret, specificReturn := fake.runStrategyReturnsOnCall[len(fake.runStrategyArgsForCall)]
	fake.runStrategyArgsForCall = append(fake.runStrategyArgsForCall, struct {
		arg1 context.Context
		arg2 strategy.Strategy
	}{arg1, arg2})
	stub := fake.RunStrategyStub
	fakeReturns := fake.runStrategyReturns
	fake.recordInvocation("RunStrategy", []interface{}{arg1, arg2})
	fake.runStrategyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) RunStrategyCallCount() int {
	fake.runStrategyMutex.RLock()
	defer fake.runStrategyMutex.RUnlock()
	return len(fake.runStrategyArgsForCall)
}

func (fake *FakeService) RunStrategyCalls(stub func(context.Context, strategy.Strategy) (uuid.UUID, error)) {
	fake.runStrategyMutex.Lock()
	defer fake.runStrategyMutex.Unlock()
	fake.RunStrategyStub = stub
}

func (fake *FakeService) RunStrategyArgsForCall(i int) (context.Context, strategy.Strategy) {
	fake.runStrategyMutex.RLock()
	defer fake.runStrategyMutex.RUnlock()
	argsForCall := fake.runStrategyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) RunStrategyReturns(result1 uuid.UUID, result2 error) {
	fake.runStrategyMutex.Lock()
	defer fake.runStrategyMutex.Unlock()
	fake.RunStrategyStub = nil
	fake.runStrategyReturns = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeService) RunStrategyReturnsOnCall(i int, result1 uuid.UUID, result2 error) {
	fake.runStrategyMutex.Lock()
	defer fake.runStrategyMutex.Unlock()
	fake.RunStrategyStub = nil
	if fake.runStrategyReturnsOnCall == nil {
		fake.runStrategyReturnsOnCall = make(map[int]struct {
			result1 uuid.UUID
			result2 error
		})
	}
	fake.runStrategyReturnsOnCall[i] = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeService) StopBacktest(arg1 uuid.UUID) error {
	fake.stopBacktestMutex.Lock()
	ret, specificReturn := fake.stopBacktestReturnsOnCall[len(fake.stopBacktestArgsForCall)]
	fake.stopBacktestArgsForCall = append(fake.stopBacktestArgsForCall, struct {
		arg1 uuid.UUID
	}{arg1})
	stub := fake.StopBacktestStub
	fakeReturns := fake.stopBacktestReturns
	fake.recordInvocation("StopBacktest", []interface{}{arg1})
	fake.stopBacktestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) StopBacktestCallCount() int {
	fake.stopBacktestMutex.RLock()
	defer fake.stopBacktestMutex.RUnlock()
	return len(fake.stopBacktestArgsForCall)
}

func (fake *FakeService) StopBacktestCalls(stub func(uuid.UUID) error) {
	fake.stopBacktestMutex.Lock()
	defer fake.stopBacktestMutex.Unlock()
	fake.StopBacktestStub = stub
}

func (fake *FakeService) StopBacktestArgsForCall(i int) uuid.UUID {
	fake.stopBacktestMutex.RLock()
	defer fake.stopBacktestMutex.RUnlock()
	argsForCall := fake.stopBacktestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) StopBacktestReturns(result1 error) {
	fake.stopBacktestMutex.Lock()
	defer fake.stopBacktestMutex.Unlock()
	fake.StopBacktestStub = nil
	fake.stopBacktestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) StopBacktestReturnsOnCall(i int, result1 error) {
	fake.stopBacktestMutex.Lock()
	defer fake.stopBacktestMutex.Unlock()
	fake.StopBacktestStub = nil
	if fake.stopBacktestReturnsOnCall == nil {
		fake.stopBacktestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.stopBacktestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) StopStrategy(arg1 context.Context, arg2 uuid.UUID) error {
	fake.stopStrategyMutex.Lock()
	ret, specificReturn := fake.stopStrategyReturnsOnCall[len(fake.stopStrategyArgsForCall)]
	fake.stopStrategyArgsForCall = append(fake.stopStrategyArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.StopStrategyStub
	fakeReturns := fake.stopStrategyReturns
	fake.recordInvocation("StopStrategy", []interface{}{arg1, arg2})
	fake.stopStrategyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) StopStrategyCallCount() int {
	fake.stopStrategyMutex.RLock()
	defer fake.stopStrategyMutex.RUnlock()
	return len(fake.stopStrategyArgsForCall)
}

func (fake *FakeService) StopStrategyCalls(stub func(context.Context, uuid.UUID) error) {
	fake.stopStrategyMutex.Lock()
	defer fake.stopStrategyMutex.Unlock()
	fake.StopStrategyStub = stub
}

func (fake *FakeService) StopStrategyArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.stopStrategyMutex.RLock()
	defer fake.stopStrategyMutex.RUnlock()
	argsForCall := fake.stopStrategyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) StopStrategyReturns(result1 error) {
	fake.stopStrategyMutex.Lock()
	defer fake.stopStrategyMutex.Unlock()
	fake.StopStrategyStub = nil
	fake.stopStrategyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) StopStrategyReturnsOnCall(i int, result1 error) {
	fake.stopStrategyMutex.Lock()
	defer fake.stopStrategyMutex.Unlock()
	fake.StopStrategyStub = nil
	if fake.stopStrategyReturnsOnCall == nil {
		fake.stopStrategyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.stopStrategyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ strategy.Service = new(FakeService)
