// Code generated by counterfeiter. DO NOT EDIT.
package meanreversionfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/prices"
)

type FakeHistoricalPriceStore struct {
	LoadHistoricalPricesStub        func(context.Context, string, time.Time, time.Time) ([]prices.AssetPrice, error)
	loadHistoricalPricesMutex       sync.RWMutex
	loadHistoricalPricesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}
	loadHistoricalPricesReturns struct {
		result1 []prices.AssetPrice
		result2 error
	}
	loadHistoricalPricesReturnsOnCall map[int]struct {
		result1 []prices.AssetPrice
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPrices(arg1 context.Context, arg2 string, arg3 time.Time, arg4 time.Time) ([]prices.AssetPrice, error) {
	fake.loadHistoricalPricesMutex.Lock()
	ret, specificReturn := fake.loadHistoricalPricesReturnsOnCall[len(fake.loadHistoricalPricesArgsForCall)]
	fake.loadHistoricalPricesArgsForCall = append(fake.loadHistoricalPricesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.LoadHistoricalPricesStub
	fakeReturns := fake.loadHistoricalPricesReturns
	fake.recordInvocation("LoadHistoricalPrices", []interface{}{arg1, arg2, arg3, arg4})
	fake.loadHistoricalPricesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPricesCallCount() int {
	fake.loadHistoricalPricesMutex.RLock()
	defer fake.loadHistoricalPricesMutex.RUnlock()
	return len(fake.loadHistoricalPricesArgsForCall)
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPricesCalls(stub func(context.Context, string, time.Time, time.Time) ([]prices.AssetPrice, error)) {
	fake.loadHistoricalPricesMutex.Lock()
	defer fake.loadHistoricalPricesMutex.Unlock()
	fake.LoadHistoricalPricesStub = stub
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPricesArgsForCall(i int) (context.Context, string, time.Time, time.Time) {
	fake.loadHistoricalPricesMutex.RLock()
	defer fake.loadHistoricalPricesMutex.RUnlock()
	argsForCall := fake.loadHistoricalPricesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPricesReturns(result1 []prices.AssetPrice, result2 error) {
	fake.loadHistoricalPricesMutex.Lock()
	defer fake.loadHistoricalPricesMutex.Unlock()
	fake.LoadHistoricalPricesStub = nil
	fake.loadHistoricalPricesReturns = struct {
		result1 []prices.AssetPrice
		result2 error
	}{result1, result2}
}

func (fake *FakeHistoricalPriceStore) LoadHistoricalPricesReturnsOnCall(i int, result1 []prices.AssetPrice, result2 error) {
	fake.loadHistoricalPricesMutex.Lock()
	defer fake.loadHistoricalPricesMutex.Unlock()
	fake.LoadHistoricalPricesStub = nil
	if fake.loadHistoricalPricesReturnsOnCall == nil {
		fake.loadHistoricalPricesReturnsOnCall = make(map[int]struct {
			result1 []prices.AssetPrice
			result2 error
		})
	}
	fake.loadHistoricalPricesReturnsOnCall[i] = struct {
		result1 []prices.AssetPrice
		result2 error
	}{result1, result2}
}

func (fake *FakeHistoricalPriceStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHistoricalPriceStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
