// Code generated by counterfeiter. DO NOT EDIT.
package meanreversionfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/candles"
)

type FakeCandleHistoryStore struct {
	CandleRangeStub        func(context.Context, string) (*time.Time, *time.Time, error)
	candleRangeMutex       sync.RWMutex
	candleRangeArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	candleRangeReturns struct {
		result1 *time.Time
		result2 *time.Time
		result3 error
	}
	candleRangeReturnsOnCall map[int]struct {
		result1 *time.Time
		result2 *time.Time
		result3 error
	}
	LoadCandlesBucketedStub        func(context.Context, string, candles.Resolution, time.Time, time.Time) ([]candles.Candle, error)
	loadCandlesBucketedMutex       sync.RWMutex
	loadCandlesBucketedArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 candles.Resolution
		arg4 time.Time
		arg5 time.Time
	}
	loadCandlesBucketedReturns struct {
		result1 []candles.Candle
		result2 error
	}
	loadCandlesBucketedReturnsOnCall map[int]struct {
		result1 []candles.Candle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCandleHistoryStore) CandleRange(arg1 context.Context, arg2 string) (*time.Time, *time.Time, error) {
	fake.candleRangeMutex.Lock()
	ret, specificReturn := fake.candleRangeReturnsOnCall[len(fake.candleRangeArgsForCall)]
	fake.candleRangeArgsForCall = append(fake.candleRangeArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CandleRangeStub
	fakeReturns := fake.candleRangeReturns
	fake.recordInvocation("CandleRange", []interface{}{arg1, arg2})
	fake.candleRangeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCandleHistoryStore) CandleRangeCallCount() int {
	fake.candleRangeMutex.RLock()
	defer fake.candleRangeMutex.RUnlock()
	return len(fake.candleRangeArgsForCall)
}

func (fake *FakeCandleHistoryStore) CandleRangeCalls(stub func(context.Context, string) (*time.Time, *time.Time, error)) {
	fake.candleRangeMutex.Lock()
	defer fake.candleRangeMutex.Unlock()
	fake.CandleRangeStub = stub
}

func (fake *FakeCandleHistoryStore) CandleRangeArgsForCall(i int) (context.Context, string) {
	fake.candleRangeMutex.RLock()
	defer fake.candleRangeMutex.RUnlock()
	argsForCall := fake.candleRangeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCandleHistoryStore) CandleRangeReturns(result1 *time.Time, result2 *time.Time, result3 error) {
	fake.candleRangeMutex.Lock()
	defer fake.candleRangeMutex.Unlock()
	fake.CandleRangeStub = nil
	fake.candleRangeReturns = struct {
		result1 *time.Time
		result2 *time.Time
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCandleHistoryStore) CandleRangeReturnsOnCall(i int, result1 *time.Time, result2 *time.Time, result3 error) {
	fake.candleRangeMutex.Lock()
	defer fake.candleRangeMutex.Unlock()
	fake.CandleRangeStub = nil
	if fake.candleRangeReturnsOnCall == nil {
		fake.candleRangeReturnsOnCall = make(map[int]struct {
			result1 *time.Time
			result2 *time.Time
			result3 error
		})
	}
	fake.candleRangeReturnsOnCall[i] = struct {
		result1 *time.Time
		result2 *time.Time
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketed(arg1 context.Context, arg2 string, arg3 candles.Resolution, arg4 time.Time, arg5 time.Time) ([]candles.Candle, error) {
	fake.loadCandlesBucketedMutex.Lock()
	ret, specificReturn := fake.loadCandlesBucketedReturnsOnCall[len(fake.loadCandlesBucketedArgsForCall)]
	fake.loadCandlesBucketedArgsForCall = append(fake.loadCandlesBucketedArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 candles.Resolution
		arg4 time.Time
		arg5 time.Time
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.LoadCandlesBucketedStub
	fakeReturns := fake.loadCandlesBucketedReturns
	fake.recordInvocation("LoadCandlesBucketed", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.loadCandlesBucketedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketedCallCount() int {
	fake.loadCandlesBucketedMutex.RLock()
	defer fake.loadCandlesBucketedMutex.RUnlock()
	return len(fake.loadCandlesBucketedArgsForCall)
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketedCalls(stub func(context.Context, string, candles.Resolution, time.Time, time.Time) ([]candles.Candle, error)) {
	fake.loadCandlesBucketedMutex.Lock()
	defer fake.loadCandlesBucketedMutex.Unlock()
	fake.LoadCandlesBucketedStub = stub
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketedArgsForCall(i int) (context.Context, string, candles.Resolution, time.Time, time.Time) {
	fake.loadCandlesBucketedMutex.RLock()
	defer fake.loadCandlesBucketedMutex.RUnlock()
	argsForCall := fake.loadCandlesBucketedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketedReturns(result1 []candles.Candle, result2 error) {
	fake.loadCandlesBucketedMutex.Lock()
	defer fake.loadCandlesBucketedMutex.Unlock()
	fake.LoadCandlesBucketedStub = nil
	fake.loadCandlesBucketedReturns = struct {
		result1 []candles.Candle
		result2 error
	}{result1, result2}
}

func (fake *FakeCandleHistoryStore) LoadCandlesBucketedReturnsOnCall(i int, result1 []candles.Candle, result2 error) {
	fake.loadCandlesBucketedMutex.Lock()
	defer fake.loadCandlesBucketedMutex.Unlock()
	fake.LoadCandlesBucketedStub = nil
	if fake.loadCandlesBucketedReturnsOnCall == nil {
		fake.loadCandlesBucketedReturnsOnCall = make(map[int]struct {
			result1 []candles.Candle
			result2 error
		})
	}
	fake.loadCandlesBucketedReturnsOnCall[i] = struct {
		result1 []candles.Candle
		result2 error
	}{result1, result2}
}

func (fake *FakeCandleHistoryStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCandleHistoryStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
