// Code generated by counterfeiter. DO NOT EDIT.
package meanreversionfakes

import (
	"context"
	"sync"

	"github.com/dora-network/dora-client-go/doraclient"
	"github.com/govalues/decimal"
)

type FakeMarketAPIClient struct {
	AssetCollateralWeightStub        func(context.Context, string) (decimal.Decimal, error)
	assetCollateralWeightMutex       sync.RWMutex
	assetCollateralWeightArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	assetCollateralWeightReturns struct {
		result1 decimal.Decimal
		result2 error
	}
	assetCollateralWeightReturnsOnCall map[int]struct {
		result1 decimal.Decimal
		result2 error
	}
	AssetPositionStub        func(context.Context, string) (decimal.Decimal, decimal.Decimal, error)
	assetPositionMutex       sync.RWMutex
	assetPositionArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	assetPositionReturns struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}
	assetPositionReturnsOnCall map[int]struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}
	BaseAssetIDStub        func(context.Context, string) (string, error)
	baseAssetIDMutex       sync.RWMutex
	baseAssetIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	baseAssetIDReturns struct {
		result1 string
		result2 error
	}
	baseAssetIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CreateMarketOrderStub        func(context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool) error
	createMarketOrderMutex       sync.RWMutex
	createMarketOrderArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 doraclient.Side
		arg4 decimal.Decimal
		arg5 decimal.Decimal
		arg6 bool
	}
	createMarketOrderReturns struct {
		result1 error
	}
	createMarketOrderReturnsOnCall map[int]struct {
		result1 error
	}
	GetPortfolioV2Stub        func(context.Context) (*doraclient.AccountPortfolioV2, error)
	getPortfolioV2Mutex       sync.RWMutex
	getPortfolioV2ArgsForCall []struct {
		arg1 context.Context
	}
	getPortfolioV2Returns struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}
	getPortfolioV2ReturnsOnCall map[int]struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}
	QuoteAssetIDStub        func(context.Context, string) (string, error)
	quoteAssetIDMutex       sync.RWMutex
	quoteAssetIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	quoteAssetIDReturns struct {
		result1 string
		result2 error
	}
	quoteAssetIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMarketAPIClient) AssetCollateralWeight(arg1 context.Context, arg2 string) (decimal.Decimal, error) {
	fake.assetCollateralWeightMutex.Lock()
	ret, specificReturn := fake.assetCollateralWeightReturnsOnCall[len(fake.assetCollateralWeightArgsForCall)]
	fake.assetCollateralWeightArgsForCall = append(fake.assetCollateralWeightArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.AssetCollateralWeightStub
	fakeReturns := fake.assetCollateralWeightReturns
	fake.recordInvocation("AssetCollateralWeight", []interface{}{arg1, arg2})
	fake.assetCollateralWeightMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) AssetCollateralWeightCallCount() int {
	fake.assetCollateralWeightMutex.RLock()
	defer fake.assetCollateralWeightMutex.RUnlock()
	return len(fake.assetCollateralWeightArgsForCall)
}

func (fake *FakeMarketAPIClient) AssetCollateralWeightCalls(stub func(context.Context, string) (decimal.Decimal, error)) {
	fake.assetCollateralWeightMutex.Lock()
	defer fake.assetCollateralWeightMutex.Unlock()
	fake.AssetCollateralWeightStub = stub
}

func (fake *FakeMarketAPIClient) AssetCollateralWeightArgsForCall(i int) (context.Context, string) {
	fake.assetCollateralWeightMutex.RLock()
	defer fake.assetCollateralWeightMutex.RUnlock()
	argsForCall := fake.assetCollateralWeightArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) AssetCollateralWeightReturns(result1 decimal.Decimal, result2 error) {
	fake.assetCollateralWeightMutex.Lock()
	defer fake.assetCollateralWeightMutex.Unlock()
	fake.AssetCollateralWeightStub = nil
	fake.assetCollateralWeightReturns = struct {
		result1 decimal.Decimal
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) AssetCollateralWeightReturnsOnCall(i int, result1 decimal.Decimal, result2 error) {
	fake.assetCollateralWeightMutex.Lock()
	defer fake.assetCollateralWeightMutex.Unlock()
	fake.AssetCollateralWeightStub = nil
	if fake.assetCollateralWeightReturnsOnCall == nil {
		fake.assetCollateralWeightReturnsOnCall = make(map[int]struct {
			result1 decimal.Decimal
			result2 error
		})
	}
	fake.assetCollateralWeightReturnsOnCall[i] = struct {
		result1 decimal.Decimal
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) AssetPosition(arg1 context.Context, arg2 string) (decimal.Decimal, decimal.Decimal, error) {
	fake.assetPositionMutex.Lock()
	ret, specificReturn := fake.assetPositionReturnsOnCall[len(fake.assetPositionArgsForCall)]
	fake.assetPositionArgsForCall = append(fake.assetPositionArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.AssetPositionStub
	fakeReturns := fake.assetPositionReturns
	fake.recordInvocation("AssetPosition", []interface{}{arg1, arg2})
	fake.assetPositionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeMarketAPIClient) AssetPositionCallCount() int {
	fake.assetPositionMutex.RLock()
	defer fake.assetPositionMutex.RUnlock()
	return len(fake.assetPositionArgsForCall)
}

func (fake *FakeMarketAPIClient) AssetPositionCalls(stub func(context.Context, string) (decimal.Decimal, decimal.Decimal, error)) {
	fake.assetPositionMutex.Lock()
	defer fake.assetPositionMutex.Unlock()
	fake.AssetPositionStub = stub
}

func (fake *FakeMarketAPIClient) AssetPositionArgsForCall(i int) (context.Context, string) {
	fake.assetPositionMutex.RLock()
	defer fake.assetPositionMutex.RUnlock()
	argsForCall := fake.assetPositionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) AssetPositionReturns(result1 decimal.Decimal, result2 decimal.Decimal, result3 error) {
	fake.assetPositionMutex.Lock()
	defer fake.assetPositionMutex.Unlock()
	fake.AssetPositionStub = nil
	fake.assetPositionReturns = struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMarketAPIClient) AssetPositionReturnsOnCall(i int, result1 decimal.Decimal, result2 decimal.Decimal, result3 error) {
	fake.assetPositionMutex.Lock()
	defer fake.assetPositionMutex.Unlock()
	fake.AssetPositionStub = nil
	if fake.assetPositionReturnsOnCall == nil {
		fake.assetPositionReturnsOnCall = make(map[int]struct {
			result1 decimal.Decimal
			result2 decimal.Decimal
			result3 error
		})
	}
	fake.assetPositionReturnsOnCall[i] = struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMarketAPIClient) BaseAssetID(arg1 context.Context, arg2 string) (string, error) {
	fake.baseAssetIDMutex.Lock()
	ret, specificReturn := fake.baseAssetIDReturnsOnCall[len(fake.baseAssetIDArgsForCall)]
	fake.baseAssetIDArgsForCall = append(fake.baseAssetIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.BaseAssetIDStub
	fakeReturns := fake.baseAssetIDReturns
	fake.recordInvocation("BaseAssetID", []interface{}{arg1, arg2})
	fake.baseAssetIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) BaseAssetIDCallCount() int {
	fake.baseAssetIDMutex.RLock()
	defer fake.baseAssetIDMutex.RUnlock()
	return len(fake.baseAssetIDArgsForCall)
}

func (fake *FakeMarketAPIClient) BaseAssetIDCalls(stub func(context.Context, string) (string, error)) {
	fake.baseAssetIDMutex.Lock()
	defer fake.baseAssetIDMutex.Unlock()
	fake.BaseAssetIDStub = stub
}

func (fake *FakeMarketAPIClient) BaseAssetIDArgsForCall(i int) (context.Context, string) {
	fake.baseAssetIDMutex.RLock()
	defer fake.baseAssetIDMutex.RUnlock()
	argsForCall := fake.baseAssetIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) BaseAssetIDReturns(result1 string, result2 error) {
	fake.baseAssetIDMutex.Lock()
	defer fake.baseAssetIDMutex.Unlock()
	fake.BaseAssetIDStub = nil
	fake.baseAssetIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) BaseAssetIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.baseAssetIDMutex.Lock()
	defer fake.baseAssetIDMutex.Unlock()
	fake.BaseAssetIDStub = nil
	if fake.baseAssetIDReturnsOnCall == nil {
		fake.baseAssetIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.baseAssetIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) CreateMarketOrder(arg1 context.Context, arg2 string, arg3 doraclient.Side, arg4 decimal.Decimal, arg5 decimal.Decimal, arg6 bool) error {
	fake.createMarketOrderMutex.Lock()
	ret, specificReturn := fake.createMarketOrderReturnsOnCall[len(fake.createMarketOrderArgsForCall)]
	fake.createMarketOrderArgsForCall = append(fake.createMarketOrderArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 doraclient.Side
		arg4 decimal.Decimal
		arg5 decimal.Decimal
		arg6 bool
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CreateMarketOrderStub
	fakeReturns := fake.createMarketOrderReturns
	fake.recordInvocation("CreateMarketOrder", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.createMarketOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMarketAPIClient) CreateMarketOrderCallCount() int {
	fake.createMarketOrderMutex.RLock()
	defer fake.createMarketOrderMutex.RUnlock()
	return len(fake.createMarketOrderArgsForCall)
}

func (fake *FakeMarketAPIClient) CreateMarketOrderCalls(stub func(context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool) error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = stub
}

func (fake *FakeMarketAPIClient) CreateMarketOrderArgsForCall(i int) (context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool) {
	fake.createMarketOrderMutex.RLock()
	defer fake.createMarketOrderMutex.RUnlock()
	argsForCall := fake.createMarketOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeMarketAPIClient) CreateMarketOrderReturns(result1 error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = nil
	fake.createMarketOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMarketAPIClient) CreateMarketOrderReturnsOnCall(i int, result1 error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = nil
	if fake.createMarketOrderReturnsOnCall == nil {
		fake.createMarketOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createMarketOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMarketAPIClient) GetPortfolioV2(arg1 context.Context) (*doraclient.AccountPortfolioV2, error) {
	fake.getPortfolioV2Mutex.Lock()
	ret, specificReturn := fake.getPortfolioV2ReturnsOnCall[len(fake.getPortfolioV2ArgsForCall)]
	fake.getPortfolioV2ArgsForCall = append(fake.getPortfolioV2ArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetPortfolioV2Stub
	fakeReturns := fake.getPortfolioV2Returns
	fake.recordInvocation("GetPortfolioV2", []interface{}{arg1})
	fake.getPortfolioV2Mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) GetPortfolioV2CallCount() int {
	fake.getPortfolioV2Mutex.RLock()
	defer fake.getPortfolioV2Mutex.RUnlock()
	return len(fake.getPortfolioV2ArgsForCall)
}

func (fake *FakeMarketAPIClient) GetPortfolioV2Calls(stub func(context.Context) (*doraclient.AccountPortfolioV2, error)) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = stub
}

func (fake *FakeMarketAPIClient) GetPortfolioV2ArgsForCall(i int) context.Context {
	fake.getPortfolioV2Mutex.RLock()
	defer fake.getPortfolioV2Mutex.RUnlock()
	argsForCall := fake.getPortfolioV2ArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMarketAPIClient) GetPortfolioV2Returns(result1 *doraclient.AccountPortfolioV2, result2 error) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = nil
	fake.getPortfolioV2Returns = struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) GetPortfolioV2ReturnsOnCall(i int, result1 *doraclient.AccountPortfolioV2, result2 error) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = nil
	if fake.getPortfolioV2ReturnsOnCall == nil {
		fake.getPortfolioV2ReturnsOnCall = make(map[int]struct {
			result1 *doraclient.AccountPortfolioV2
			result2 error
		})
	}
	fake.getPortfolioV2ReturnsOnCall[i] = struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) QuoteAssetID(arg1 context.Context, arg2 string) (string, error) {
	fake.quoteAssetIDMutex.Lock()
	ret, specificReturn := fake.quoteAssetIDReturnsOnCall[len(fake.quoteAssetIDArgsForCall)]
	fake.quoteAssetIDArgsForCall = append(fake.quoteAssetIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.QuoteAssetIDStub
	fakeReturns := fake.quoteAssetIDReturns
	fake.recordInvocation("QuoteAssetID", []interface{}{arg1, arg2})
	fake.quoteAssetIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) QuoteAssetIDCallCount() int {
	fake.quoteAssetIDMutex.RLock()
	defer fake.quoteAssetIDMutex.RUnlock()
	return len(fake.quoteAssetIDArgsForCall)
}

func (fake *FakeMarketAPIClient) QuoteAssetIDCalls(stub func(context.Context, string) (string, error)) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = stub
}

func (fake *FakeMarketAPIClient) QuoteAssetIDArgsForCall(i int) (context.Context, string) {
	fake.quoteAssetIDMutex.RLock()
	defer fake.quoteAssetIDMutex.RUnlock()
	argsForCall := fake.quoteAssetIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) QuoteAssetIDReturns(result1 string, result2 error) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = nil
	fake.quoteAssetIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) QuoteAssetIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = nil
	if fake.quoteAssetIDReturnsOnCall == nil {
		fake.quoteAssetIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.quoteAssetIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMarketAPIClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
