// Code generated by counterfeiter. DO NOT EDIT.
package candlesfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/candles"
)

type FakeCandleStore struct {
	GetLastTimestampStub        func(context.Context, string) (*time.Time, error)
	getLastTimestampMutex       sync.RWMutex
	getLastTimestampArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getLastTimestampReturns struct {
		result1 *time.Time
		result2 error
	}
	getLastTimestampReturnsOnCall map[int]struct {
		result1 *time.Time
		result2 error
	}
	SaveCandlesStub        func(context.Context, []candles.StreamCandlesEntry) error
	saveCandlesMutex       sync.RWMutex
	saveCandlesArgsForCall []struct {
		arg1 context.Context
		arg2 []candles.StreamCandlesEntry
	}
	saveCandlesReturns struct {
		result1 error
	}
	saveCandlesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCandleStore) GetLastTimestamp(arg1 context.Context, arg2 string) (*time.Time, error) {
	fake.getLastTimestampMutex.Lock()
	ret, specificReturn := fake.getLastTimestampReturnsOnCall[len(fake.getLastTimestampArgsForCall)]
	fake.getLastTimestampArgsForCall = append(fake.getLastTimestampArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetLastTimestampStub
	fakeReturns := fake.getLastTimestampReturns
	fake.recordInvocation("GetLastTimestamp", []interface{}{arg1, arg2})
	fake.getLastTimestampMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCandleStore) GetLastTimestampCallCount() int {
	fake.getLastTimestampMutex.RLock()
	defer fake.getLastTimestampMutex.RUnlock()
	return len(fake.getLastTimestampArgsForCall)
}

func (fake *FakeCandleStore) GetLastTimestampCalls(stub func(context.Context, string) (*time.Time, error)) {
	fake.getLastTimestampMutex.Lock()
	defer fake.getLastTimestampMutex.Unlock()
	fake.GetLastTimestampStub = stub
}

func (fake *FakeCandleStore) GetLastTimestampArgsForCall(i int) (context.Context, string) {
	fake.getLastTimestampMutex.RLock()
	defer fake.getLastTimestampMutex.RUnlock()
	argsForCall := fake.getLastTimestampArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCandleStore) GetLastTimestampReturns(result1 *time.Time, result2 error) {
	fake.getLastTimestampMutex.Lock()
	defer fake.getLastTimestampMutex.Unlock()
	fake.GetLastTimestampStub = nil
	fake.getLastTimestampReturns = struct {
		result1 *time.Time
		result2 error
	}{result1, result2}
}

func (fake *FakeCandleStore) GetLastTimestampReturnsOnCall(i int, result1 *time.Time, result2 error) {
	fake.getLastTimestampMutex.Lock()
	defer fake.getLastTimestampMutex.Unlock()
	fake.GetLastTimestampStub = nil
	if fake.getLastTimestampReturnsOnCall == nil {
		fake.getLastTimestampReturnsOnCall = make(map[int]struct {
			result1 *time.Time
			result2 error
		})
	}
	fake.getLastTimestampReturnsOnCall[i] = struct {
		result1 *time.Time
		result2 error
	}{result1, result2}
}

func (fake *FakeCandleStore) SaveCandles(arg1 context.Context, arg2 []candles.StreamCandlesEntry) error {
	var arg2Copy []candles.StreamCandlesEntry
	if arg2 != nil {
		arg2Copy = make([]candles.StreamCandlesEntry, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.saveCandlesMutex.Lock()
	ret, specificReturn := fake.saveCandlesReturnsOnCall[len(fake.saveCandlesArgsForCall)]
	fake.saveCandlesArgsForCall = append(fake.saveCandlesArgsForCall, struct {
		arg1 context.Context
		arg2 []candles.StreamCandlesEntry
	}{arg1, arg2Copy})
	stub := fake.SaveCandlesStub
	fakeReturns := fake.saveCandlesReturns
	fake.recordInvocation("SaveCandles", []interface{}{arg1, arg2Copy})
	fake.saveCandlesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCandleStore) SaveCandlesCallCount() int {
	fake.saveCandlesMutex.RLock()
	defer fake.saveCandlesMutex.RUnlock()
	return len(fake.saveCandlesArgsForCall)
}

func (fake *FakeCandleStore) SaveCandlesCalls(stub func(context.Context, []candles.StreamCandlesEntry) error) {
	fake.saveCandlesMutex.Lock()
	defer fake.saveCandlesMutex.Unlock()
	fake.SaveCandlesStub = stub
}

func (fake *FakeCandleStore) SaveCandlesArgsForCall(i int) (context.Context, []candles.StreamCandlesEntry) {
	fake.saveCandlesMutex.RLock()
	defer fake.saveCandlesMutex.RUnlock()
	argsForCall := fake.saveCandlesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCandleStore) SaveCandlesReturns(result1 error) {
	fake.saveCandlesMutex.Lock()
	defer fake.saveCandlesMutex.Unlock()
	fake.SaveCandlesStub = nil
	fake.saveCandlesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCandleStore) SaveCandlesReturnsOnCall(i int, result1 error) {
	fake.saveCandlesMutex.Lock()
	defer fake.saveCandlesMutex.Unlock()
	fake.SaveCandlesStub = nil
	if fake.saveCandlesReturnsOnCall == nil {
		fake.saveCandlesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveCandlesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCandleStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCandleStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ candles.CandleStore = new(FakeCandleStore)
