// Code generated by counterfeiter. DO NOT EDIT.
package pricesfakes

import (
	"context"
	"sync"

	"github.com/dora-network/bond-trading-strategies/prices"
	"github.com/google/uuid"
)

type FakePriceStore struct {
	SavePricesStub        func(context.Context, map[uuid.UUID]prices.AssetPrice) error
	savePricesMutex       sync.RWMutex
	savePricesArgsForCall []struct {
		arg1 context.Context
		arg2 map[uuid.UUID]prices.AssetPrice
	}
	savePricesReturns struct {
		result1 error
	}
	savePricesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePriceStore) SavePrices(arg1 context.Context, arg2 map[uuid.UUID]prices.AssetPrice) error {
	fake.savePricesMutex.Lock()
	ret, specificReturn := fake.savePricesReturnsOnCall[len(fake.savePricesArgsForCall)]
	fake.savePricesArgsForCall = append(fake.savePricesArgsForCall, struct {
		arg1 context.Context
		arg2 map[uuid.UUID]prices.AssetPrice
	}{arg1, arg2})
	stub := fake.SavePricesStub
	fakeReturns := fake.savePricesReturns
	fake.recordInvocation("SavePrices", []interface{}{arg1, arg2})
	fake.savePricesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePriceStore) SavePricesCallCount() int {
	fake.savePricesMutex.RLock()
	defer fake.savePricesMutex.RUnlock()
	return len(fake.savePricesArgsForCall)
}

func (fake *FakePriceStore) SavePricesCalls(stub func(context.Context, map[uuid.UUID]prices.AssetPrice) error) {
	fake.savePricesMutex.Lock()
	defer fake.savePricesMutex.Unlock()
	fake.SavePricesStub = stub
}

func (fake *FakePriceStore) SavePricesArgsForCall(i int) (context.Context, map[uuid.UUID]prices.AssetPrice) {
	fake.savePricesMutex.RLock()
	defer fake.savePricesMutex.RUnlock()
	argsForCall := fake.savePricesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePriceStore) SavePricesReturns(result1 error) {
	fake.savePricesMutex.Lock()
	defer fake.savePricesMutex.Unlock()
	fake.SavePricesStub = nil
	fake.savePricesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePriceStore) SavePricesReturnsOnCall(i int, result1 error) {
	fake.savePricesMutex.Lock()
	defer fake.savePricesMutex.Unlock()
	fake.SavePricesStub = nil
	if fake.savePricesReturnsOnCall == nil {
		fake.savePricesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.savePricesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePriceStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePriceStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prices.PriceStore = new(FakePriceStore)
