// Package strategy defines the core domain types for the bond mean-reversion
// trading strategy prototype.
//
// Mean reversion in bonds exploits the tendency of yield spreads (the difference
// between a bond's yield-to-maturity and a benchmark rate) to return to their
// historical average after a significant deviation.  When the spread is much
// wider than its rolling mean the bond is "cheap" relative to the benchmark and
// we expect the spread to narrow — we BUY.  When it is much tighter we SELL.
// Position size is scaled by how many standard deviations the spread has moved
// from its mean (the z-score).
package types

import (
	"time"

	"github.com/govalues/decimal"
)

// Signal is the trading action the strategy recommends for a bond.
type Signal int

const (
	SignalHold Signal = iota // within the neutral band — do nothing
	SignalBuy                // spread too wide — bond is cheap, expect convergence
	SignalSell               // spread too tight — bond is rich, expect reversion
)

func (s Signal) String() string {
	switch s {
	case SignalBuy:
		return "BUY"
	case SignalSell:
		return "SELL"
	default:
		return "HOLD"
	}
}

// YieldObservation is a single timestamped yield-spread reading for one bond.
// The spread is the bond's YTM minus the risk-free benchmark yield (e.g. the
// equivalent-maturity Treasury yield).
type YieldObservation struct {
	Time   time.Time
	BondID string
	// YTM is the bond's current yield-to-maturity expressed as a decimal
	// (e.g. 0.055 for 5.5 %).
	YTM decimal.Decimal
	// BenchmarkYield is the risk-free benchmark yield for the same tenor.
	BenchmarkYield decimal.Decimal
	// Price is the bond's clean price at observation time, used for position
	// sizing (converting dollar budgets into bond quantities).
	Price decimal.Decimal
}

// Spread returns YTM − BenchmarkYield.  A positive spread means the bond
// yields more than the benchmark (it is "cheap"); a negative spread means it
// yields less (it is "rich").
func (o YieldObservation) Spread() (decimal.Decimal, error) {
	return o.YTM.Sub(o.BenchmarkYield)
}

// Decision is the full output of one strategy evaluation step.
type Decision struct {
	Time   time.Time
	BondID string

	// YTM is the bond's current yield-to-maturity.
	YTM decimal.Decimal
	// BenchmarkYield is the risk-free benchmark yield for the same tenor.
	BenchmarkYield decimal.Decimal
	// Spread is YTM − BenchmarkYield.
	Spread decimal.Decimal
	// RollingMean is the rolling mean of the spread over the lookback window.
	RollingMean decimal.Decimal
	// RollingStdDev is the rolling standard deviation of the spread over the
	// lookback window.
	RollingStdDev decimal.Decimal
	// ZScore is (Spread − RollingMean) / RollingStdDev.
	ZScore decimal.Decimal

	// Price is the bond price at decision time, used for position sizing.
	Price decimal.Decimal

	// Signal is the recommended action.
	Signal Signal
	// PositionSize is a fraction of capital in [0, MaxPositionSize] suggested
	// for the trade. It is proportional to the absolute z-score above the
	// entry threshold, capped at MaxPositionSize.
	PositionSize decimal.Decimal
}

// TradeRecord captures a single simulated trade event (entry or exit)
// produced by the backtester.
type TradeRecord struct {
	Time         time.Time
	BondID       string
	Signal       Signal
	Spread       decimal.Decimal
	PositionSize decimal.Decimal
	ZScore       decimal.Decimal
	// Price is the bond price at which this trade was executed.
	Price decimal.Decimal
	// Quantity is the number of bonds traded (computed from the budget and
	// entry price).
	Quantity decimal.Decimal
	// EntryBalance is the remaining balance at the time the position was
	// opened, captured before any entry-side cash-flow adjustment.
	EntryBalance decimal.Decimal
}

// Exit reason constants for ClosedTrade.
const (
	ExitReasonTakeProfit = "take_profit"
	ExitReasonStopLoss   = "stop_loss"
	ExitReasonForceClose = "force_close"
)

// ClosedTrade records a completed round-trip trade and its PnL.
// PnL is expressed in spread-point terms: (EntrySpread − ExitSpread) for a BUY
// (we profited if the spread narrowed) or (ExitSpread − EntrySpread) for a SELL
// (we profited if the spread widened back).  Positive PnL = profit.
type ClosedTrade struct {
	BondID       string
	OpenTime     time.Time
	CloseTime    time.Time
	Signal       Signal // direction of the opening trade
	ExitSignal   Signal // signal generated by the strategy at exit time
	EntrySpread  decimal.Decimal
	ExitSpread   decimal.Decimal
	EntryZScore  decimal.Decimal
	ExitZScore   decimal.Decimal
	PositionSize decimal.Decimal
	PnL          decimal.Decimal
	ExitReason   string
	// EntryPrice is the bond price at which the position was opened.
	EntryPrice decimal.Decimal
	// ExitPrice is the bond price at which the position was closed.
	ExitPrice decimal.Decimal
	// Quantity is the number of bonds traded.
	Quantity decimal.Decimal
	// EntryBalance is the remaining balance at the time the position was
	// opened, before the trade budget was deducted. PnL is computed from
	// this value rather than from Quantity so that PositionSize only
	// controls position sizing and does not scale the PnL.
	EntryBalance decimal.Decimal
}

// BacktestResult summarises a full backtest run.
type BacktestResult struct {
	ClosedTrades []ClosedTrade
	TradeRecords []TradeRecord
	TotalPnL     decimal.Decimal
	WinCount     int
	LossCount    int
	MaxDrawdown  decimal.Decimal
	SharpeRatio  decimal.Decimal // annualised, assumes daily observations
	Err          error
}
