// Code generated by counterfeiter. DO NOT EDIT.
package copytradingfakes

import (
	"context"
	"sync"
	"time"

	"github.com/dora-network/bond-trading-strategies/strategy/copytrading"
)

type FakeTradesHistoryStore struct {
	StreamTradesStub        func(context.Context, string, time.Time, time.Time) (<-chan copytrading.Trade, <-chan error)
	streamTradesMutex       sync.RWMutex
	streamTradesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}
	streamTradesReturns struct {
		result1 <-chan copytrading.Trade
		result2 <-chan error
	}
	streamTradesReturnsOnCall map[int]struct {
		result1 <-chan copytrading.Trade
		result2 <-chan error
	}
	TradeBoundsStub        func(context.Context, string) (time.Time, time.Time, int, error)
	tradeBoundsMutex       sync.RWMutex
	tradeBoundsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	tradeBoundsReturns struct {
		result1 time.Time
		result2 time.Time
		result3 int
		result4 error
	}
	tradeBoundsReturnsOnCall map[int]struct {
		result1 time.Time
		result2 time.Time
		result3 int
		result4 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTradesHistoryStore) StreamTrades(arg1 context.Context, arg2 string, arg3 time.Time, arg4 time.Time) (<-chan copytrading.Trade, <-chan error) {
	fake.streamTradesMutex.Lock()
	ret, specificReturn := fake.streamTradesReturnsOnCall[len(fake.streamTradesArgsForCall)]
	fake.streamTradesArgsForCall = append(fake.streamTradesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.StreamTradesStub
	fakeReturns := fake.streamTradesReturns
	fake.recordInvocation("StreamTrades", []interface{}{arg1, arg2, arg3, arg4})
	fake.streamTradesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTradesHistoryStore) StreamTradesCallCount() int {
	fake.streamTradesMutex.RLock()
	defer fake.streamTradesMutex.RUnlock()
	return len(fake.streamTradesArgsForCall)
}

func (fake *FakeTradesHistoryStore) StreamTradesCalls(stub func(context.Context, string, time.Time, time.Time) (<-chan copytrading.Trade, <-chan error)) {
	fake.streamTradesMutex.Lock()
	defer fake.streamTradesMutex.Unlock()
	fake.StreamTradesStub = stub
}

func (fake *FakeTradesHistoryStore) StreamTradesArgsForCall(i int) (context.Context, string, time.Time, time.Time) {
	fake.streamTradesMutex.RLock()
	defer fake.streamTradesMutex.RUnlock()
	argsForCall := fake.streamTradesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeTradesHistoryStore) StreamTradesReturns(result1 <-chan copytrading.Trade, result2 <-chan error) {
	fake.streamTradesMutex.Lock()
	defer fake.streamTradesMutex.Unlock()
	fake.StreamTradesStub = nil
	fake.streamTradesReturns = struct {
		result1 <-chan copytrading.Trade
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeTradesHistoryStore) StreamTradesReturnsOnCall(i int, result1 <-chan copytrading.Trade, result2 <-chan error) {
	fake.streamTradesMutex.Lock()
	defer fake.streamTradesMutex.Unlock()
	fake.StreamTradesStub = nil
	if fake.streamTradesReturnsOnCall == nil {
		fake.streamTradesReturnsOnCall = make(map[int]struct {
			result1 <-chan copytrading.Trade
			result2 <-chan error
		})
	}
	fake.streamTradesReturnsOnCall[i] = struct {
		result1 <-chan copytrading.Trade
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeTradesHistoryStore) TradeBounds(arg1 context.Context, arg2 string) (time.Time, time.Time, int, error) {
	fake.tradeBoundsMutex.Lock()
	ret, specificReturn := fake.tradeBoundsReturnsOnCall[len(fake.tradeBoundsArgsForCall)]
	fake.tradeBoundsArgsForCall = append(fake.tradeBoundsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.TradeBoundsStub
	fakeReturns := fake.tradeBoundsReturns
	fake.recordInvocation("TradeBounds", []interface{}{arg1, arg2})
	fake.tradeBoundsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4
}

func (fake *FakeTradesHistoryStore) TradeBoundsCallCount() int {
	fake.tradeBoundsMutex.RLock()
	defer fake.tradeBoundsMutex.RUnlock()
	return len(fake.tradeBoundsArgsForCall)
}

func (fake *FakeTradesHistoryStore) TradeBoundsCalls(stub func(context.Context, string) (time.Time, time.Time, int, error)) {
	fake.tradeBoundsMutex.Lock()
	defer fake.tradeBoundsMutex.Unlock()
	fake.TradeBoundsStub = stub
}

func (fake *FakeTradesHistoryStore) TradeBoundsArgsForCall(i int) (context.Context, string) {
	fake.tradeBoundsMutex.RLock()
	defer fake.tradeBoundsMutex.RUnlock()
	argsForCall := fake.tradeBoundsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTradesHistoryStore) TradeBoundsReturns(result1 time.Time, result2 time.Time, result3 int, result4 error) {
	fake.tradeBoundsMutex.Lock()
	defer fake.tradeBoundsMutex.Unlock()
	fake.TradeBoundsStub = nil
	fake.tradeBoundsReturns = struct {
		result1 time.Time
		result2 time.Time
		result3 int
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeTradesHistoryStore) TradeBoundsReturnsOnCall(i int, result1 time.Time, result2 time.Time, result3 int, result4 error) {
	fake.tradeBoundsMutex.Lock()
	defer fake.tradeBoundsMutex.Unlock()
	fake.TradeBoundsStub = nil
	if fake.tradeBoundsReturnsOnCall == nil {
		fake.tradeBoundsReturnsOnCall = make(map[int]struct {
			result1 time.Time
			result2 time.Time
			result3 int
			result4 error
		})
	}
	fake.tradeBoundsReturnsOnCall[i] = struct {
		result1 time.Time
		result2 time.Time
		result3 int
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeTradesHistoryStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTradesHistoryStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
