// Code generated by counterfeiter. DO NOT EDIT.
package copytradingfakes

import (
	"context"
	"sync"

	"github.com/dora-network/dora-client-go/doraclient"
	"github.com/govalues/decimal"
)

type FakeMarketAPIClient struct {
	CreateMarketOrderStub        func(context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool, string) error
	createMarketOrderMutex       sync.RWMutex
	createMarketOrderArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 doraclient.Side
		arg4 decimal.Decimal
		arg5 decimal.Decimal
		arg6 bool
		arg7 string
	}
	createMarketOrderReturns struct {
		result1 error
	}
	createMarketOrderReturnsOnCall map[int]struct {
		result1 error
	}
	GetAssetPositionStub        func(context.Context, string) (decimal.Decimal, decimal.Decimal, error)
	getAssetPositionMutex       sync.RWMutex
	getAssetPositionArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getAssetPositionReturns struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}
	getAssetPositionReturnsOnCall map[int]struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}
	GetPortfolioV2Stub        func(context.Context) (*doraclient.AccountPortfolioV2, error)
	getPortfolioV2Mutex       sync.RWMutex
	getPortfolioV2ArgsForCall []struct {
		arg1 context.Context
	}
	getPortfolioV2Returns struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}
	getPortfolioV2ReturnsOnCall map[int]struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}
	QuoteAssetIDStub        func(context.Context, string) (string, error)
	quoteAssetIDMutex       sync.RWMutex
	quoteAssetIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	quoteAssetIDReturns struct {
		result1 string
		result2 error
	}
	quoteAssetIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMarketAPIClient) CreateMarketOrder(arg1 context.Context, arg2 string, arg3 doraclient.Side, arg4 decimal.Decimal, arg5 decimal.Decimal, arg6 bool, arg7 string) error {
	fake.createMarketOrderMutex.Lock()
	ret, specificReturn := fake.createMarketOrderReturnsOnCall[len(fake.createMarketOrderArgsForCall)]
	fake.createMarketOrderArgsForCall = append(fake.createMarketOrderArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 doraclient.Side
		arg4 decimal.Decimal
		arg5 decimal.Decimal
		arg6 bool
		arg7 string
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	stub := fake.CreateMarketOrderStub
	fakeReturns := fake.createMarketOrderReturns
	fake.recordInvocation("CreateMarketOrder", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.createMarketOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMarketAPIClient) CreateMarketOrderCallCount() int {
	fake.createMarketOrderMutex.RLock()
	defer fake.createMarketOrderMutex.RUnlock()
	return len(fake.createMarketOrderArgsForCall)
}

func (fake *FakeMarketAPIClient) CreateMarketOrderCalls(stub func(context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool, string) error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = stub
}

func (fake *FakeMarketAPIClient) CreateMarketOrderArgsForCall(i int) (context.Context, string, doraclient.Side, decimal.Decimal, decimal.Decimal, bool, string) {
	fake.createMarketOrderMutex.RLock()
	defer fake.createMarketOrderMutex.RUnlock()
	argsForCall := fake.createMarketOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakeMarketAPIClient) CreateMarketOrderReturns(result1 error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = nil
	fake.createMarketOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMarketAPIClient) CreateMarketOrderReturnsOnCall(i int, result1 error) {
	fake.createMarketOrderMutex.Lock()
	defer fake.createMarketOrderMutex.Unlock()
	fake.CreateMarketOrderStub = nil
	if fake.createMarketOrderReturnsOnCall == nil {
		fake.createMarketOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createMarketOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMarketAPIClient) GetAssetPosition(arg1 context.Context, arg2 string) (decimal.Decimal, decimal.Decimal, error) {
	fake.getAssetPositionMutex.Lock()
	ret, specificReturn := fake.getAssetPositionReturnsOnCall[len(fake.getAssetPositionArgsForCall)]
	fake.getAssetPositionArgsForCall = append(fake.getAssetPositionArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetAssetPositionStub
	fakeReturns := fake.getAssetPositionReturns
	fake.recordInvocation("GetAssetPosition", []interface{}{arg1, arg2})
	fake.getAssetPositionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeMarketAPIClient) GetAssetPositionCallCount() int {
	fake.getAssetPositionMutex.RLock()
	defer fake.getAssetPositionMutex.RUnlock()
	return len(fake.getAssetPositionArgsForCall)
}

func (fake *FakeMarketAPIClient) GetAssetPositionCalls(stub func(context.Context, string) (decimal.Decimal, decimal.Decimal, error)) {
	fake.getAssetPositionMutex.Lock()
	defer fake.getAssetPositionMutex.Unlock()
	fake.GetAssetPositionStub = stub
}

func (fake *FakeMarketAPIClient) GetAssetPositionArgsForCall(i int) (context.Context, string) {
	fake.getAssetPositionMutex.RLock()
	defer fake.getAssetPositionMutex.RUnlock()
	argsForCall := fake.getAssetPositionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) GetAssetPositionReturns(result1 decimal.Decimal, result2 decimal.Decimal, result3 error) {
	fake.getAssetPositionMutex.Lock()
	defer fake.getAssetPositionMutex.Unlock()
	fake.GetAssetPositionStub = nil
	fake.getAssetPositionReturns = struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMarketAPIClient) GetAssetPositionReturnsOnCall(i int, result1 decimal.Decimal, result2 decimal.Decimal, result3 error) {
	fake.getAssetPositionMutex.Lock()
	defer fake.getAssetPositionMutex.Unlock()
	fake.GetAssetPositionStub = nil
	if fake.getAssetPositionReturnsOnCall == nil {
		fake.getAssetPositionReturnsOnCall = make(map[int]struct {
			result1 decimal.Decimal
			result2 decimal.Decimal
			result3 error
		})
	}
	fake.getAssetPositionReturnsOnCall[i] = struct {
		result1 decimal.Decimal
		result2 decimal.Decimal
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMarketAPIClient) GetPortfolioV2(arg1 context.Context) (*doraclient.AccountPortfolioV2, error) {
	fake.getPortfolioV2Mutex.Lock()
	ret, specificReturn := fake.getPortfolioV2ReturnsOnCall[len(fake.getPortfolioV2ArgsForCall)]
	fake.getPortfolioV2ArgsForCall = append(fake.getPortfolioV2ArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetPortfolioV2Stub
	fakeReturns := fake.getPortfolioV2Returns
	fake.recordInvocation("GetPortfolioV2", []interface{}{arg1})
	fake.getPortfolioV2Mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) GetPortfolioV2CallCount() int {
	fake.getPortfolioV2Mutex.RLock()
	defer fake.getPortfolioV2Mutex.RUnlock()
	return len(fake.getPortfolioV2ArgsForCall)
}

func (fake *FakeMarketAPIClient) GetPortfolioV2Calls(stub func(context.Context) (*doraclient.AccountPortfolioV2, error)) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = stub
}

func (fake *FakeMarketAPIClient) GetPortfolioV2ArgsForCall(i int) context.Context {
	fake.getPortfolioV2Mutex.RLock()
	defer fake.getPortfolioV2Mutex.RUnlock()
	argsForCall := fake.getPortfolioV2ArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMarketAPIClient) GetPortfolioV2Returns(result1 *doraclient.AccountPortfolioV2, result2 error) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = nil
	fake.getPortfolioV2Returns = struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) GetPortfolioV2ReturnsOnCall(i int, result1 *doraclient.AccountPortfolioV2, result2 error) {
	fake.getPortfolioV2Mutex.Lock()
	defer fake.getPortfolioV2Mutex.Unlock()
	fake.GetPortfolioV2Stub = nil
	if fake.getPortfolioV2ReturnsOnCall == nil {
		fake.getPortfolioV2ReturnsOnCall = make(map[int]struct {
			result1 *doraclient.AccountPortfolioV2
			result2 error
		})
	}
	fake.getPortfolioV2ReturnsOnCall[i] = struct {
		result1 *doraclient.AccountPortfolioV2
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) QuoteAssetID(arg1 context.Context, arg2 string) (string, error) {
	fake.quoteAssetIDMutex.Lock()
	ret, specificReturn := fake.quoteAssetIDReturnsOnCall[len(fake.quoteAssetIDArgsForCall)]
	fake.quoteAssetIDArgsForCall = append(fake.quoteAssetIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.QuoteAssetIDStub
	fakeReturns := fake.quoteAssetIDReturns
	fake.recordInvocation("QuoteAssetID", []interface{}{arg1, arg2})
	fake.quoteAssetIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMarketAPIClient) QuoteAssetIDCallCount() int {
	fake.quoteAssetIDMutex.RLock()
	defer fake.quoteAssetIDMutex.RUnlock()
	return len(fake.quoteAssetIDArgsForCall)
}

func (fake *FakeMarketAPIClient) QuoteAssetIDCalls(stub func(context.Context, string) (string, error)) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = stub
}

func (fake *FakeMarketAPIClient) QuoteAssetIDArgsForCall(i int) (context.Context, string) {
	fake.quoteAssetIDMutex.RLock()
	defer fake.quoteAssetIDMutex.RUnlock()
	argsForCall := fake.quoteAssetIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMarketAPIClient) QuoteAssetIDReturns(result1 string, result2 error) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = nil
	fake.quoteAssetIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) QuoteAssetIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.quoteAssetIDMutex.Lock()
	defer fake.quoteAssetIDMutex.Unlock()
	fake.QuoteAssetIDStub = nil
	if fake.quoteAssetIDReturnsOnCall == nil {
		fake.quoteAssetIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.quoteAssetIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMarketAPIClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMarketAPIClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
